services:

  db:
    image: postgres:17.5-alpine3.21
    restart: no

    env_file:
      - .env

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    
    volumes:
      - postgres_db:/var/lib/postgresql/data

    ports:
      - "${POSTGRES_PORT}:5432"

  pgAdmin:
    image: dpage/pgadmin4:9.5.0
    restart: no
    ports:
      - ${PGADMIN_PORT}:80

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  

    depends_on:
      - db

    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_db:
  pgadmin-data:
