# Generated by Django 5.2.7 on 2025-10-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('byline', models.CharField(blank=True, max_length=255, null=True)),
                ('topic_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('alt_text', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('resizer_url', models.URLField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('basic_headline', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('canonical_url', models.URLField()),
                ('website', models.CharField(max_length=100)),
                ('published_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
                ('display_time', models.DateTimeField()),
                ('read_minutes', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('article_type', models.CharField(blank=True, max_length=100, null=True)),
                ('content_code', models.CharField(blank=True, max_length=100, null=True)),
                ('source_name', models.CharField(max_length=100)),
                ('company_rics', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_tag_text', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_tag_url', models.URLField(blank=True, null=True)),
                ('kicker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kicker_path', models.URLField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='parser_app.author')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser_app.thumbnail')),
            ],
        ),
    ]
